config/routes.rb
Rails.application.routes.draw do
  root to: 'forms#new'
  
  devise_for :admins
  
  devise_scope :admin do
    resources :admins, only: [:show]
  end

  resources :forms, only: [:create, :new]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form.rb
class Form < ApplicationRecord
  before_save :normalize_fields
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  VALID_MOBILE_REGEX = /^[0-9]{10}$/

  validates_presence_of :full_name, :occupation, :title, :nationality
  validates :email, uniqueness: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, allow_nil: true
  validates :mobile, format: { with: VALID_MOBILE_REGEX, multiline: true }
  

  private

  def normalize_fields
    self.full_name = full_name.titleize unless full_name.blank?
    self.email = email.downcase unless email.blank?
    self.occupation = occupation.titleize unless occupation.blank?
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_admin, only: :show
  before_action :prevent_access, only: :show

  def show
    @list = Form.all
    @total = @list.count
    @males = Form.where("title = ?", 'Male').count
    @females = Form.where("title = ?", 'Female').count    
  end

  private
    def set_admin
      @admin = Admin.find(params[:id])
    end

    def prevent_access
      render_404 unless current_admin
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def render_404
    respond_to do |format|
      format.html do
        render file: Rails.root.join("public", "404"), layout: false, status: "404"
      end
      format.any { head :not_found }
    end
  end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :re_route 

  def new
    @form = Form.new
  end
  
  def create
    @form = Form.new(forms_params)
    if @form.save
      flash[:success] = "Information successfully saved."
      redirect_back fallback_location: root_path
    else
      render :new
    end
  end

  private

    def forms_params
      params.require(:form).permit(:title, :occupation, :nationality, :full_name, :mobile, :email)
    end

    def re_route
      redirect_to current_admin unless !current_admin and return 
      flash[:warning] = "You can't access that page because you're logged in. Log out to view that"
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
  def gender_select
    ['Male', 'Female']
  end

   def countries
    
    [
      'United States', 'Nigeria', 'Afghanistan', 'Åland Islands', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Anguilla',
      'Antarctica', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
      'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia',
      'Bonaire, Sint Eustatius and Saba', 'Bosnia and Herzegovina', 'Botswana', 'Bouvet Island', 'Brazil', 'British Indian Ocean Territory',
      'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Cayman Islands', 
      'Central African Republic', 'Chad', 'Chile', 'China', 'Christmas Island', 'Cocos (Keeling) Islands', 'Colombia', 'Comoros', 'Congo',
      'Cook Islands', 'Costa Rica', 'Côte d\'Ivoire', 'Croatia', 'Cuba', 'Curaçao', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti',
      'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 
      'Falkland Islands (Malvinas)', 'Faroe Islands', 'Fiji', 'Finland', 'France', 'French Guiana', 'French Polynesia', 'French Southern Territories', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guadeloupe',
      'Guam', 'Guatemala', 'Guernsey', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Heard Island and McDonald Islands', 
      'Holy See (Vatican City State)', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland',
      'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Korea', 'Korea (North)',
      'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macao', 'Macedonia', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius', 'Mayotte', 'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Montserrat', 'Morocco',
      'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Niue', 'Norfolk Island', 'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Palestinian Territory', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Pitcairn', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Réunion', 'Romania', 
      'Russian Federation', 'Rwanda', 'Saint Barthélemy', 'Saint Helena', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Martin (French part)', 'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Georgia and the South Sandwich Islands', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Svalbard and Jan Mayen', 'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'Virgin Islands (British)', 'Virgin Islands (U.S.)', 'Wallis and Futuna', 'Western Sahara', 'Yemen', 'Zambia', 'Zimbabwe', 'Other'
    ]
  
  end
end

app/views/admins/show.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
  <a class="navbar-brand" href="#">Mobex '17</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item active">
       <a href="<%= destroy_admin_session_path %>" data-method="delete" rel="nofollow" class="nav-link">Sign Out</a>
      </li>
    </ul>
  </div>
  </nav>


  <div class="container">
  <div class="row">
    <div class="col-md-2" style="margin-top: 20px;">
      Males: <span> <%= @males %> </span> <br>
      Females: <span> <%= @females %> </span> <br>
      Total: <span> <%= @total %> </span>
    </div>
    <div class="col-md-9">
    <%= render 'shared/flash_message' %>
    <center> <h4 style="margin-top: 20px; margin-bottom: 20px;">Registered Students</h4> </center>
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Full Name</th>
            <th>Email</th>
            <th>Occupation</th>
            <th>Nationality</th>
            <th>Phone number</th>
          </tr>
        </thead>

        <tbody>
         <% @list.each_with_index do |list, count|%>
          <% count += 1 %>
          <tr>
            <th scope="row"> <%= count %> </th>
            <td> <%= list.full_name %> </td>
            <td> <%= list.email %> </td>
            <td> <%= list.occupation %> </td>
            <td> <%= list.nationality %> </td>
            <td> <%= list.mobile %> </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  </div>
</div>

app/views/forms/new.html.erb
<style>
  body {
    background-image: url('assets/bg.svg');
    background-size: cover;
  }
</style>


<div class="container">
  <h2 class="text-center m-t-50 text-white">MOBEX '17 </h2>
  <div class="row m-t-40">
    <div class="col d-flex justify-content-center">
      <div class="card" style="width: 25rem;">
        <div class="card-body">

          <%= form_for(@form, url: forms_path) do |f| %>
          
            <div class="text-center">
              <h5 class="text-uppercase" style="margin-bottom: 2px;">Registration Form</h4> <hr>
            </div> 
            <%= render 'shared/error_message', object: f.object %>
            <%= render 'shared/flash_message' %>

              <div class="form-group">
                <%= f.label :full_name %>
                <%= f.text_field :full_name, class: 'form-control', placeholder: 'Miracle Anyanwu' %>
              </div>

            <div class="form-group">
              <%= f.label :gender %>
              <%= f.select :title, options_for_select(gender_select), { prompt: "Select Gender" }, class: "form-control" %>
            </div>
                
            <div class="form-group">
              <%= f.label :occupation %>
              <%= f.text_field :occupation, class: 'form-control', placeholder: 'Student' %>
            </div>

            <div class="form-group">
              <%= f.label :nationality %>
              <%= f.select :nationality, options_for_select(countries), { prompt: "Select Nationality" }, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :email %>
              <%= f.email_field :email, class: 'form-control', placeholder: 'anyanwumiracle78@gmail.com' %>
            </div>

            <div class="form-group">
              <%= f.label :mobile_number %>
              <%= f.text_field :mobile, class: 'form-control', placeholder: '0509289409' %>
            </div>

            <%= f.submit "Submit", class: 'btn btn-success btn-block' %>
            <% end %>
            </div>
          </div>
        </div>
    </div>
  </div>

</div>           
                

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mobexform</title>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Registering for Mobex" />
    <meta name="author" content="Miracle Anyanwu">
    <script async src = "https://www.googletagmanager.com/gtag/js?id=UA-102233335-3"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() { dataLayer.push(arguments) };
      gtag('js', new Date());
      gtag('config', 'UA-102233335-3');
    </script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <%= yield %>

    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </body>
</html>

app/views/shared/_devise_flash.html.erb
<% if flash[:notice] %>
	<div class="alert alert-info">
		<button type="button" class="close">
			&times;
		</button>
		<%= notice %>
	</div>
<% end %>

<% if flash[:alert] %>
	<div class="alert alert-danger">
		<button type="button" class="close">
			&times;
		</button>
		<%= flash[:alert] %>
	</div>
<% end %>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>

    <div id="error_explanation">

      <div class="alert alert-danger" role="alert">
         <span style="font-size: 15px;"> <%= pluralize(object.errors.count, "error") %> prohibited this form from being sent. </span>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <ul>
          <% object.errors.full_messages.each do |msg| %>
            <li>
              <span style="font-size: 13px;"> <%= msg %> </span>
            </li>
          <% end %>
      </ul>
      </div>
    </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true"> &times; </span>
          </button>
          <%= message %>
        </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
    <footer class="m-t-30">
        <div class="container">
            <ul class="list-inline">
                <li class="list-inline-item">
                    
                </li>
                <li class="footer-menu-divider list-inline-item"></li>
                <li class="list-inline-item">
                    
                </li>
                <li class="footer-menu-divider list-inline-item"></li>
                <li class="list-inline-item">
                    
                </li>
                <li class="footer-menu-divider list-inline-item"></li>
                <li class="list-inline-item">
                    
                </li>
                <li class="footer-menu-divider list-inline-item"></li>
                <li class="list-inline-item">
                    
                </li>
            </ul>
            <p class="copyright text-muted small text-center">
              <span class="text-white">&copy; 2017. Crafted by</span> <a href="https://polymathwhiz.github.io" target="_blank"><b>PolymathWhiz</b></a>
            </p>
        </div>
    </footer>